-- Generated by MigrationScaffoldGenerator
-- Compared against: tenant schemas
-- Review before applying. Additive changes are the supported path.

UPDATE bookings
SET review_eligible = TRUE,
    review_eligible_at = COALESCE(review_eligible_at, end_date)
WHERE status = 'COMPLETED'
  AND review_submitted_at IS NULL
  AND COALESCE(review_eligible, FALSE) = FALSE;
