-- Generated by MigrationScaffoldGenerator
-- Compared against: tenant schemas
-- Review before applying. Additive changes are the supported path.

ALTER TABLE driver_licenses
    ADD COLUMN IF NOT EXISTS verified BOOLEAN;
