-- Generated by MigrationScaffoldGenerator
-- Compared against: tenant schemas
-- Review before applying. Additive changes are the supported path.

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS just_testinggg VARCHAR(255);
