-- Generated by MigrationScaffoldGenerator
-- Compared against: tenant schemas
-- Review before applying. Additive changes are the supported path.

ALTER TABLE bookings
    DROP COLUMN IF EXISTS just_testinggg;
