-- Generated by MigrationScaffoldGenerator
-- Compared against: tenant schemas
-- Review before applying. Additive changes are the supported path.

ALTER TABLE vehicle_categories
    DROP COLUMN IF EXISTS image_url;
