-- Generated by MigrationScaffoldGenerator
-- Compared against: tenant schemas
-- Review before applying. Additive changes are the supported path.

ALTER TABLE addons
    ADD COLUMN IF NOT EXISTS quantity INTEGER;
