-- Generated by MigrationScaffoldGenerator
-- Compared against: tenant schemas
-- Review before applying. Additive changes are the supported path.

ALTER TABLE addons
    DROP COLUMN IF EXISTS just_testing;

ALTER TABLE payments
    DROP COLUMN IF EXISTS just_testing;

ALTER TABLE vehicle_categories
    DROP COLUMN IF EXISTS image_url;
