-- Generated by MigrationScaffoldGenerator
-- Compared against: tenant schemas
-- Review before applying. Additive changes are the supported path.

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS review_eligible BOOLEAN;

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS review_eligible_at TIMESTAMP;

ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS review_submitted_at TIMESTAMP;
