-- Generated by MigrationScaffoldGenerator
-- Compared against schema: public
-- Review before applying. Additive changes are the supported path.

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS just_testing VARCHAR(255);
