-- Generated by MigrationScaffoldGenerator
-- Compared against: public schema
-- Review before applying. Additive changes are the supported path.

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS fake_age INTEGER;
