-- Generated by MigrationScaffoldGenerator
-- Compared against: public schema
-- Review before applying. Additive changes are the supported path.

ALTER TABLE public.users
    DROP COLUMN IF EXISTS fake_age;
