-- Generated by MigrationScaffoldGenerator
-- Compared against schema: public
-- Review before applying. Additive changes are the supported path.

ALTER TABLE public.tenants
    DROP COLUMN IF EXISTS is_impersonate;

ALTER TABLE public.users
    DROP COLUMN IF EXISTS just_testing;
